# from https://github.com/RepoCamp/ohsu2018/blob/master/.travis.yml
language: ruby
sudo: false
cache:
  bundler: true
rvm:
  - 2.5.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rake db:create db:setup

services:
  - redis-server

script: xvfb-run -a bundle exec rake ci
